### ISSUE TITLE
デバイスをグルーピングできるようにする

### ISSUE THREAD

**Issue by hygogg** [hiroumi/manacam#1]
- 可能なら、1つのデバイスが複数のグループに属せるようにする。
　- コスト（時間）がかかるなら、1デバイス1グループのみでもよい。
　- いまのところグループは入れ子にできなくていい。
- グループ内のデバイスの合算を表示できるようにする。

**Comment by hiroumi** [comment]
デフォルトのグループを表示から消すことができないので、不要なグループは消せるようにしたいです。

![image](https://user-images.githubusercontent.com/8373414/123792564-b8a38280-d91b-11eb-8147-67ebff1e3fa4.png)
