### ISSUE TITLE
ユーザー向けページ追加

### ISSUE THREAD

**Issue by hygogg** [hiroumi/manacam#8]
会社単位で、施設利用者向けに現在の混み具合がわかる簡易参照ページを表示できるようにする。
社員など関係者だけに見せるユースケースがあるので、認証をかけられるようにする。
認証は、会社単位でのID・パスワード認証想定（basic認証？）
認証の有無とID・パスワードを管理画面から設定できるようにする。
カウント表示はグループ単位とする。
表示するのは、当日の最新集計単位。
カウント表示のほか、グループごとに定義したカウント（総数・最大・平均）の上限に対する％表示ができるようにする。
20%刻みくらいで色を変えて表示できるようにする。（100%だと赤いとか）
グループ&カウント単位毎の上限値を管理画面から設定できるようにする。

**Comment by hiroumi** [comment]
ユーザー向けページ で、各デバイスごとの利用率（最大10人固定）が表示されるようになっていますが、
http://manacam.net/company/user/1?count_type=max
こちらを
・デバイス単位でなく、グループ単位での表示
・グループごとの最大値を、10人から、任意の人数を指定可能とする
ようにアップデート・修正をお願いします。
(内部的には、デバイス単位で持っておいたほうが、あとあと良さそうですね。
こちらは、まずはグループ単位でリリースをするよりも、デバイス単位でのリリースをするほうが
やりやすいようであれば、そちらを優先していただいて良いです）
